main/urls.py
from django.urls import path
from main.views import show_main, create_entry, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register, login_user, logout_user
from main.views import increment_flower_amount, decrement_flower_amount, delete_flower
from main.views import get_flower_json, add_flower_ajax
from main.views import create_product_flutter
app_name = 'main'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('', show_main, name='show_main'),
    path('create-entry', create_entry, name='create_entry'),
    path('int-flower/<int:pk_id>/', increment_flower_amount, name='inc_flower'),
    path('dec-flower/<int:pk_id>/', decrement_flower_amount, name='dec_flower'),
    path('del-flower/<int:pk_id>/', delete_flower, name='del_flower'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('get-flower/', get_flower_json, name='get_flower_json'),
    path('create-flower-ajax/', add_flower_ajax, name='add_flower_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

memory_bouquet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), 
    path('auth/', include('authentication.urls')),
] 

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Flower(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

class Cake(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Flower

class FlowerForm(ModelForm):
    class Meta:
        model = Flower
        fields = ["name", "amount", "description"]

main/views.py
import datetime
import json
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from main.forms import FlowerForm
from django.urls import reverse
from django.shortcuts import render
from main.models import Flower, Cake
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {
        'form':form,
        'owner_name': 'Alma Laras Bestari',
        'npm': '2206082303',
        'class': 'PBP E',
        'application': 'Memory Bouquet',
        }
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {
        'owner_name': 'Alma Laras Bestari',
        'npm': '2206082303',
        'class': 'PBP E',
        'application': 'Memory Bouquet',
    }
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def show_main(request):
    flowers = Flower.objects.filter(user=request.user)

    total_entries = len(flowers)
    if (total_entries > 1):
        entry_messages = f'You have a total of {total_entries} entries'
    else:
        entry_messages = f'You have a total of {total_entries} entry'

    context = {
        'owner_name': 'Alma Laras Bestari',
        'npm': '2206082303',
        'class': 'PBP E',
        'application': 'Memory Bouquet',
        'name': request.user.username,
        'flowers': flowers,
        'total_entry_message': entry_messages,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, "main.html", context)

def get_flower_json(request):
    flowers = Flower.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', flowers))

@csrf_exempt
def add_flower_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Flower(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def create_entry(request):
    form = FlowerForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        entry = form.save(commit=False)
        entry.user = request.user
        entry.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
        'owner_name': 'Alma Laras Bestari',
        'npm': '2206082303',
        'class': 'PBP E',
        'application': 'Memory Bouquet',
    }
    return render(request, "create_entry.html", context)

def increment_flower_amount(request, pk_id):
    if request.method == 'POST':
        flower = Flower.objects.get(id=pk_id)
        flower.amount += 1
        flower.save()
    
    return redirect('main:show_main')

def decrement_flower_amount(request, pk_id):
    if request.method == 'POST':
        flower = Flower.objects.get(id=pk_id)
        if flower.amount > 0:
            flower.amount -= 1
            flower.save()
    
    return redirect('main:show_main')

def delete_flower(request, pk_id):
    if request.method == 'POST':
        flower = Flower.objects.get(id=pk_id)
        flower.delete()
    
    return redirect('main:show_main')

def show_xml(request):
    data = Flower.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Flower.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Flower.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Flower.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Flower.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_entry.html
{% extends 'base.html' %} 
{% block content %}

<div class="header">
    <p class="information">{{ owner_name }} | {{ npm }} | {{ class }}</p>
    <h1>{{ application }}</h1>
    <h2>a collection of flowers from humanity</h2>
</div>

<div class="flower-input">
<h1>Add New Entry</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Entry"/>
            </td>
        </tr>
    </table>
</form>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
    <div class="header">
        <p class="information">{{ owner_name }} | {{ npm }} | {{ class }}</p>
        <h1>{{ application }}</h1>
        <h2>a collection of flowers from humanity</h2>
    </div>

<div class = "login">
    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
   <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
    </head>
<body>
    <div class="header">
        <p class="information">{{ owner_name }} | {{ npm }} | {{ class }}</p>
        <h1>{{ application }}</h1>
        <h2>a collection of flowers from humanity</h2>
    </div>
    <!--Code adapted from w3schools HTML Table Borders -->
    <div class="container">
        <div class ="greetings">
            <h1>Welcome {{ name }} 𓇢𓆸</h1>
            <span>Sesi terakhir login: {{ last_login }}</span>
        </div>

        <p class="total-entry">{{ total_entry_message}}</p>

        <div id="modal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title">Add New Entry</h1>
                </div>
                <div class="modal-body">
                    <form id="form" method="POST">
                        {% csrf_token %}
                        <table class="table">
                            <tr>
                                <td><label for="name">Name:</label></td>
                                <td><input type="text" id="name" name="name"></td>
                            </tr>
                            <tr>
                                <td><label for="amount">Amount:</label></td>
                                <td><input type="number" id="amount" name="amount"></td>
                            </tr>
                            <tr>
                                <td><label for="description">Description:</label></td>
                                <td><textarea id="description" name="description"></textarea></td>
                            </tr>
                        </table>
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="close-button" class="btn-secondary">Close</button>
                    <button id="button-add" class="btn-primary">Add Entry</button>
                </div>
            </div>
        </div>
        <button id="open-modal" class="btn-primary">Add Entry</button>
        

        <a href="{% url 'main:logout' %}">
            <button>
                Logout
            </button>
        </a>
        
        <div id="flower-card" class="card-container" data-dec-url="{% url 'main:dec_flower' 0 %}" data-inc-url="{% url 'main:inc_flower' 0 %}" data-del-url="{% url 'main:del_flower' 0 %}">
        </div>
    </div>
    </body>
</html>

<script>
    async function getFlowers() {
        return fetch("{% url 'main:get_flower_json' %}").then((res) => res.json())
    }

    async function refreshFlowers() {
    document.getElementById("flower-card").innerHTML = "";
    const flowers = await getFlowers();

    const decUrl = "{% url 'main:dec_flower' 0 %}";
    const incUrl = "{% url 'main:inc_flower' 0 %}";
    const delUrl = "{% url 'main:del_flower' 0 %}";
        
    flowers.forEach((flower, index, arr) => {
        const card = document.createElement("div");
        card.classList.add("card");


        const cardContent = `
            <h5>${flower.fields.name}</h5>
            <p style="font-size: 10px; margin: 0px 20px 10px 0px;">
                ${flower.fields.date_added}</p>
            <p>Amount: ${flower.fields.amount}</p>
            <p>${flower.fields.description}</p>

            <form action="${incUrl.replace('0', flower.pk)}" method="POST">
                {% csrf_token %}
                <button class="inc-dec-button" type="submit">+</button>
            </form>
            <form action="${decUrl.replace('0', flower.pk)}" method="POST">
                {% csrf_token %}
                <button class="inc-dec-button" type="submit">-</button>
            </form>
            <form action="${delUrl.replace('0', flower.pk)}" method="POST">
                {% csrf_token %}
                <button class="del-button" type="submit">
                    <span>Delete</span>
                </button>
            </form>
        `;

        card.innerHTML = cardContent;

        if (index === flowers.length - 1) {
            card.classList.add("last-card"); // Add a CSS class for the last card
        }

        document.getElementById("flower-card").appendChild(card);
    });
    }

    refreshFlowers()

    // taken from W3Schools because I am not using bootstrap ^^
    const modal = document.getElementById("modal");
    const btn = document.getElementById("open-modal");
    const span = document.getElementById("close-button");

    btn.addEventListener("click", function() {
        modal.style.display = "block";
    });

    span.addEventListener("click", function() {
        modal.style.display = "none";
    });

    window.onclick = function(event) {
        if (event.target === modal) {
            modal.style.display = "none";
        }
    };


    function addFlower(event) {
        fetch("{% url 'main:add_flower_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        })
        .then(response => {
            if (response.ok) {
                modal.style.display = "none";
                document.getElementById("form").reset();
                refreshFlowers();
            }
        });

        return false
    }

    document.getElementById("button-add").onclick = addFlower;


</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class="header">
    <p class="information">{{ owner_name }} | {{ npm }} | {{ class }}</p>
    <h1>{{ application }}</h1>
    <h2>a collection of flowers from humanity</h2>
</div>

<div class = "register">
    <h1>Register</h1>  
        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}